import type { Product } from "../domain/product";
import { dollarsToCents } from "../domain/units";

const LEGROOM = 400;

const legroom = (label: string) =>
  [{ face: "front", depthMm: LEGROOM, reason: "seating_approach", label }] as const;

export const SEATING: readonly Product[] = [
  {
    id: "brenlo-loveseat-1400",
    name: "Brenlo Loveseat 1400",
    category: "sofa",
    widthMm: 1400,
    depthMm: 850,
    heightMm: 820,
    priceCents: dollarsToCents(899),
    styleTags: ["linen", "scandinavian", "compact"],
    clearances: legroom("Legroom in front of the seat"),
    blurb: "A two-cushion loveseat sized for apartments and narrow living rooms.",
  },
  {
    id: "aldsjo-2-seat-sofa",
    name: "Aldsjo 2-Seat Sofa",
    category: "sofa",
    widthMm: 1600,
    depthMm: 900,
    heightMm: 850,
    priceCents: dollarsToCents(1249),
    styleTags: ["linen", "minimal", "scandinavian"],
    clearances: legroom("Legroom in front of the seat"),
    blurb: "A clean-lined two-seater in a hard-wearing oatmeal linen weave.",
  },
  {
    id: "aldsjo-3-seat-sofa",
    name: "Aldsjo 3-Seat Sofa",
    category: "sofa",
    widthMm: 2200,
    depthMm: 950,
    heightMm: 850,
    priceCents: dollarsToCents(1899),
    styleTags: ["linen", "minimal", "warm timber"],
    clearances: legroom("Legroom in front of the seat"),
    blurb: "The three-seat Aldsjo on tapered oak legs, deep enough to lounge in.",
  },
  {
    id: "korvane-leather-sofa-2400",
    name: "Korvane Leather Sofa 2400",
    category: "sofa",
    widthMm: 2400,
    depthMm: 980,
    heightMm: 800,
    priceCents: dollarsToCents(2899),
    styleTags: ["leather", "mid-century", "walnut"],
    clearances: legroom("Legroom in front of the seat"),
    blurb: "Full-grain tan leather over a walnut frame that softens with use.",
  },
  {
    id: "havlund-sectional-2900",
    name: "Havlund Sectional 2900",
    category: "sofa",
    widthMm: 2900,
    depthMm: 1650,
    heightMm: 840,
    priceCents: dollarsToCents(3499),
    styleTags: ["boucle", "scandinavian", "minimal"],
    clearances: legroom("Legroom in front of the seat and chaise"),
    blurb: "A large boucle sectional with a right-hand chaise for open-plan rooms.",
  },

  {
    id: "vesmo-boucle-armchair",
    name: "Vesmo Boucle Armchair",
    category: "armchair",
    widthMm: 780,
    depthMm: 800,
    heightMm: 780,
    priceCents: dollarsToCents(699),
    styleTags: ["boucle", "scandinavian", "compact"],
    clearances: legroom("Legroom in front of the seat"),
    blurb: "A rounded boucle tub chair that tucks into a reading corner.",
  },
  {
    id: "lorvik-lounge-chair",
    name: "Lorvik Lounge Chair",
    category: "armchair",
    widthMm: 880,
    depthMm: 900,
    heightMm: 820,
    priceCents: dollarsToCents(1099),
    styleTags: ["leather", "mid-century", "walnut"],
    clearances: legroom("Legroom in front of the seat"),
    blurb: "A low-slung leather lounge chair on a solid walnut base.",
  },
  {
    id: "tannby-dining-chair",
    name: "Tannby Dining Chair",
    category: "dining_chair",
    widthMm: 460,
    depthMm: 520,
    heightMm: 880,
    priceCents: dollarsToCents(129),
    styleTags: ["light oak", "scandinavian", "compact"],
    clearances: [],
    blurb: "A stackable light-oak side chair with a shaped plywood back.",
  },
  {
    id: "grennas-upholstered-chair",
    name: "Grennas Upholstered Chair",
    category: "dining_chair",
    widthMm: 500,
    depthMm: 560,
    heightMm: 860,
    priceCents: dollarsToCents(199),
    styleTags: ["linen", "warm timber", "minimal"],
    clearances: [],
    blurb: "A padded linen seat on ash legs for longer dinners.",
  },
  {
    id: "kalvern-metal-chair",
    name: "Kalvern Metal Chair",
    category: "dining_chair",
    widthMm: 440,
    depthMm: 500,
    heightMm: 810,
    priceCents: dollarsToCents(89),
    styleTags: ["black metal", "industrial", "compact"],
    clearances: [],
    blurb: "A powder-coated steel cafe chair that stacks four high.",
  },

  {
    id: "norlen-task-chair",
    name: "Norlen Task Chair",
    category: "office_chair",
    widthMm: 620,
    depthMm: 620,
    heightMm: 1000,
    priceCents: dollarsToCents(299),
    styleTags: ["black metal", "minimal", "compact"],
    clearances: [],
    blurb: "A mesh-back task chair with height and tilt adjustment.",
  },
  {
    id: "ostrand-ergonomic-chair",
    name: "Ostrand Ergonomic Chair",
    category: "office_chair",
    widthMm: 700,
    depthMm: 700,
    heightMm: 1250,
    priceCents: dollarsToCents(749),
    styleTags: ["black metal", "industrial", "minimal"],
    clearances: [],
    blurb: "A fully adjustable headrest chair for full working days.",
  },
];
