import type { Product } from "../domain/product";
import { dollarsToCents } from "../domain/units";

export const SOFT: readonly Product[] = [
  {
    id: "birkholm-rug-1700",
    name: "Birkholm Rug 1700",
    category: "rug",
    widthMm: 1700,
    depthMm: 1200,
    heightMm: 12,
    priceCents: dollarsToCents(229),
    styleTags: ["linen", "coastal", "compact"],
    clearances: [],
    blurb: "A flatweave wool rug sized to sit under a coffee table.",
  },
  {
    id: "birkholm-rug-2400",
    name: "Birkholm Rug 2400",
    category: "rug",
    widthMm: 2400,
    depthMm: 1700,
    heightMm: 14,
    priceCents: dollarsToCents(499),
    styleTags: ["linen", "scandinavian", "coastal"],
    clearances: [],
    blurb: "The living-room size, wide enough to catch the front legs of a sofa.",
  },
  {
    id: "sundane-shag-rug-3000",
    name: "Sundane Shag Rug 3000",
    category: "rug",
    widthMm: 3000,
    depthMm: 2000,
    heightMm: 20,
    priceCents: dollarsToCents(849),
    styleTags: ["boucle", "warm timber", "minimal"],
    clearances: [],
    blurb: "A deep-pile rug that anchors a large open-plan seating zone.",
  },

  {
    id: "ekvall-floor-lamp",
    name: "Ekvall Floor Lamp",
    category: "floor_lamp",
    widthMm: 400,
    depthMm: 400,
    heightMm: 1600,
    priceCents: dollarsToCents(149),
    styleTags: ["black metal", "minimal", "compact"],
    clearances: [],
    blurb: "A slim black column lamp with a fabric drum shade.",
  },
  {
    id: "torbeck-arc-lamp",
    name: "Torbeck Arc Lamp",
    category: "floor_lamp",
    widthMm: 750,
    depthMm: 450,
    heightMm: 1950,
    priceCents: dollarsToCents(329),
    styleTags: ["brushed brass", "mid-century", "minimal"],
    clearances: [],
    blurb: "A brass arc lamp that reaches over a sofa without a side table.",
  },
  {
    id: "havso-rattan-lamp",
    name: "Havso Rattan Lamp",
    category: "floor_lamp",
    widthMm: 420,
    depthMm: 420,
    heightMm: 1500,
    priceCents: dollarsToCents(199),
    styleTags: ["rattan", "coastal", "warm timber"],
    clearances: [],
    blurb: "A woven rattan shade on a light timber tripod base.",
  },
];
