import type { ClearanceRequirement, Product } from "../domain/product";
import { dollarsToCents } from "../domain/units";

/** AS 1428-style circulation: 900mm lets a diner slide a chair back and pass behind it. */
const DINING_PULLOUT: readonly ClearanceRequirement[] = (
  ["front", "back", "left", "right"] as const
).map((face) => ({
  face,
  depthMm: 900,
  reason: "chair_pullout" as const,
  label: "Diners need 900mm to pull a chair out and walk behind it",
}));

const DESK_APPROACH: readonly ClearanceRequirement[] = [
  {
    face: "front",
    depthMm: 900,
    reason: "seating_approach",
    label: "Room for an office chair to be pulled back from the desk",
  },
];

const BEDSIDE_DRAWER: readonly ClearanceRequirement[] = [
  {
    face: "front",
    depthMm: 300,
    reason: "drawer_pull",
    label: "Shallow drawer needs 300mm to open",
  },
];

export const TABLES: readonly Product[] = [
  {
    id: "solvig-coffee-table-1100",
    name: "Solvig Coffee Table 1100",
    category: "coffee_table",
    widthMm: 1100,
    depthMm: 600,
    heightMm: 400,
    priceCents: dollarsToCents(349),
    styleTags: ["light oak", "scandinavian", "minimal"],
    clearances: [],
    blurb: "An oak-veneer rectangle with a slatted lower shelf for magazines.",
  },
  {
    id: "brekka-round-coffee-table",
    name: "Brekka Round Coffee Table",
    category: "coffee_table",
    widthMm: 800,
    depthMm: 800,
    heightMm: 420,
    priceCents: dollarsToCents(249),
    styleTags: ["warm timber", "minimal", "compact"],
    clearances: [],
    blurb: "A small round table that suits tight seating arrangements.",
  },
  {
    id: "hedmark-coffee-table-1300",
    name: "Hedmark Coffee Table 1300",
    category: "coffee_table",
    widthMm: 1300,
    depthMm: 700,
    heightMm: 380,
    priceCents: dollarsToCents(629),
    styleTags: ["walnut", "mid-century", "brushed brass"],
    clearances: [],
    blurb: "A wide walnut table on splayed legs with brass sabots.",
  },

  {
    id: "verrin-dining-table-1200",
    name: "Verrin Dining Table 1200",
    category: "dining_table",
    widthMm: 1200,
    depthMm: 800,
    heightMm: 740,
    priceCents: dollarsToCents(549),
    styleTags: ["light oak", "scandinavian", "compact"],
    clearances: DINING_PULLOUT,
    blurb: "A four-seat oak table proportioned for small dining nooks.",
  },
  {
    id: "verrin-dining-table-1800",
    name: "Verrin Dining Table 1800",
    category: "dining_table",
    widthMm: 1800,
    depthMm: 900,
    heightMm: 740,
    priceCents: dollarsToCents(1149),
    styleTags: ["light oak", "scandinavian", "minimal"],
    clearances: DINING_PULLOUT,
    blurb: "The six-seat Verrin, with a solid oak top and trestle base.",
  },
  {
    id: "eldmark-dining-table-2400",
    name: "Eldmark Dining Table 2400",
    category: "dining_table",
    widthMm: 2400,
    depthMm: 1000,
    heightMm: 740,
    priceCents: dollarsToCents(2299),
    styleTags: ["warm timber", "mid-century", "walnut"],
    clearances: DINING_PULLOUT,
    blurb: "A generous eight-seat table for households that entertain.",
  },
  {
    id: "runnas-round-dining-table",
    name: "Runnas Round Dining Table",
    category: "dining_table",
    widthMm: 1100,
    depthMm: 1100,
    heightMm: 750,
    priceCents: dollarsToCents(699),
    styleTags: ["warm timber", "minimal", "compact"],
    clearances: DINING_PULLOUT,
    blurb: "A four-seat pedestal round with no corner legs to knock.",
  },
  {
    id: "torvik-bistro-table-800",
    name: "Torvik Bistro Table 800",
    category: "dining_table",
    widthMm: 800,
    depthMm: 800,
    heightMm: 745,
    priceCents: dollarsToCents(399),
    styleTags: ["black metal", "industrial", "compact"],
    clearances: DINING_PULLOUT,
    blurb: "A two-seat steel-base bistro square for balconies and studios.",
  },

  {
    id: "myrbo-desk-1200",
    name: "Myrbo Desk 1200",
    category: "desk",
    widthMm: 1200,
    depthMm: 600,
    heightMm: 740,
    priceCents: dollarsToCents(399),
    styleTags: ["light oak", "minimal", "scandinavian"],
    clearances: DESK_APPROACH,
    blurb: "A plain oak-topped desk with a cable tray along the back rail.",
  },
  {
    id: "myrbo-compact-desk-900",
    name: "Myrbo Compact Desk 900",
    category: "desk",
    widthMm: 900,
    depthMm: 500,
    heightMm: 740,
    priceCents: dollarsToCents(249),
    styleTags: ["light oak", "compact", "minimal"],
    clearances: DESK_APPROACH,
    blurb: "A slim desk for a hallway nook or bedroom corner.",
  },
  {
    id: "stennas-desk-1600",
    name: "Stennas Desk 1600",
    category: "desk",
    widthMm: 1600,
    depthMm: 700,
    heightMm: 740,
    priceCents: dollarsToCents(749),
    styleTags: ["black metal", "industrial", "walnut"],
    clearances: DESK_APPROACH,
    blurb: "A wide dual-monitor desk on a black steel A-frame.",
  },
  {
    id: "granlid-corner-desk",
    name: "Granlid Corner Desk",
    category: "desk",
    widthMm: 1400,
    depthMm: 1400,
    heightMm: 745,
    priceCents: dollarsToCents(879),
    styleTags: ["warm timber", "black metal", "minimal"],
    clearances: DESK_APPROACH,
    blurb: "An L-shaped desk that turns an unused corner into a workstation.",
  },

  {
    id: "nallby-bedside-table",
    name: "Nallby Bedside Table",
    category: "bedside_table",
    widthMm: 450,
    depthMm: 400,
    heightMm: 550,
    priceCents: dollarsToCents(129),
    styleTags: ["light oak", "compact", "scandinavian"],
    clearances: BEDSIDE_DRAWER,
    blurb: "A single-drawer bedside in light oak with a lower open shelf.",
  },
  {
    id: "fjelra-open-bedside",
    name: "Fjelra Open Bedside",
    category: "bedside_table",
    widthMm: 400,
    depthMm: 350,
    heightMm: 520,
    priceCents: dollarsToCents(79),
    styleTags: ["black metal", "compact", "minimal"],
    clearances: [],
    blurb: "An open wire-frame bedside with no drawer to swing clear of.",
  },
];
